### ISSUE TITLE
Добавление ссылки в подводке 

### ISSUE THREAD

**Issue by Hit1ove** [antonlukin/social-planner#2]
Можно ли убрать автоматическое добавление ссылки в подводке для соц. сетей?

Иногда нужно вставить ссылку в начале, или наоборот, как-то ее обрамить, можно ли убрать автоматическое добавление линки?

Заранее спасибо за ответ.

**Comment by antonlukin** [comment]
Привет!
Да, можно. Для этого есть фильтр `social_poster_prepare_message`.

```
/**
 * @param array  $message Sending message data.
 * @param string $target  Target provider name.
 * @param array  $task    Scheduled task data.
 */
function my_prepare_message( $message, $target, $task ) {
    unset( $message['link'] );

    return $message;
}

add_filter( 'social_poster_prepare_message', 'my_prepare_message', 10, 3 );
```

Этот код нужно добавить либо в файл темы `functions.php`, либо создать свой плагин (можно [mu-plugin](https://wordpress.org/support/article/must-use-plugins/)) 
Чуть подробнее об этом в документации к плагину: https://wpget.org/social-planner/hooks/#social_poster_prepare_message

Хорошего дня, обращайтесь, если будут еще вопросы – задачу пока не закрываю.

**Comment by Hit1ove** [comment]
Спасибо, этого решения мне хватает.

**Comment by hackerspace-team** [comment]
Использовал этот фильтр но он почему то не работает 
Ссылка так же идет в соц сети 

/**
 * @param array  $message Sending message data.
 * @param string $target  Target provider name.
 * @param array  $task    Scheduled task data.
 */
function my_prepare_message( $message, $target, $task ) {
    unset( $message['link'] );

    return $message;
}

add_filter( 'social_poster_prepare_message', 'my_prepare_message', 10, 3 );

**Comment by antonlukin** [comment]
@hackerspace-team попробуйте заменить его на хук social_planner_prepare_message. 
В одном из обновлений было изменено его название.
